#!/bin/bash
touch file.txt
echo "-\('-')/- hhhaaahahahahhahahahahahahahahahhhhhhaaaaaaaahhahahahahahahahahahahahahahahahahahhahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahhahahahahahahahahhhahahahahahahhahahahahhahhhhahahahahahahahahahahahahahahahhhhhhhhaaaaaaahahahahahahaahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahhahhahahahahahahahahahahahhahahahahahahahahahahahahahahahahahshahahahahahahahahahahahahahahaha" > file.txt
while true
do
	cat file.txt
done